version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:10.16.0
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - save_cache:
          key: yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}
          paths:
            - ~/.cache/yarn
      - save_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}
          paths:
            - node_modules
      - run:
          name: Run tests
          command: yarn run test
      - run:
          name: Build Android Release
          command: cd android && ./gradlew assembleRelease
      - run:
          name: release bundle AAB file
          command: cd android && ./gradlew bundleRelease
      - run:
          name: Upload APK file
          with:
            name: app-release.apk
            path: android/app/build/outputs/apk/release/